# Generated by Django 3.1.3 on 2020-11-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction, French Poetry etc.)', max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='requests',
            options={'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы'},
        ),
        migrations.RemoveField(
            model_name='requests',
            name='categories',
        ),
        migrations.AlterField(
            model_name='requests',
            name='is_anonimous',
            field=models.BooleanField(verbose_name='Анонимно'),
        ),
        migrations.AddField(
            model_name='requests',
            name='categories',
            field=models.ManyToManyField(help_text='Select a genre for this book', to='main.Category'),
        ),
    ]
